In [72]:
import pandas as pd
import numpy as np

In [73]:
dates = pd.date_range(
    start="2025-11-09 00:00:00",
    end="2025-11-12 00:00:00",
    freq="H",
    inclusive="left"   
)

df_axe= pd.DataFrame({'datetime': dates})

df_axe['date'] = df_axe['datetime'].dt.date
df_axe['heure'] = df_axe['datetime'].dt.hour
df_axe['dow'] = df_axe['datetime'].dt.dayofweek
df_axe['mois'] = df_axe['datetime'].dt.month
df_axe['annee'] = df_axe['datetime'].dt.year
df_axe['jour_mois'] = df_axe['datetime'].dt.day
jour_map = {0:'Lun',1:'Mar',2:'Mer',3:'Jeu',4:'Ven',5:'Sam',6:'Dim'}
df_axe['jour_semaine'] = df_axe['dow'].map(jour_map)

df_axe['heure_sin'] = np.sin(2 * np.pi * df_axe['heure'] / 24)
df_axe['heure_cos'] = np.cos(2 * np.pi * df_axe['heure'] / 24)

df_axe['jour_sin'] = np.sin(2 * np.pi * df_axe['dow'] / 7)
df_axe['jour_cos'] = np.cos(2 * np.pi * df_axe['dow'] / 7)

df_axe['mois_sin'] = np.sin(2 * np.pi * df_axe['mois'] / 12)
df_axe['mois_cos'] = np.cos(2 * np.pi * df_axe['mois'] / 12)

df_axe.head(10)

/var/folders/qc/5qn44xzs143g6s6sy04v51qm0000gn/T/ipykernel_7220/861596580.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range(

,datetime,date,heure,dow,mois,annee,jour_mois,jour_semaine,heure_sin,heure_cos,jour_sin,jour_cos,mois_sin,mois_cos
0,2025-11-09 00:00:00,2025-11-09,0,6,11,2025,9,Dim,0.000000,1.000000e+00,-0.781831,0.62349,-0.5,0.866025
1,2025-11-09 01:00:00,2025-11-09,1,6,11,2025,9,Dim,0.258819,9.659258e-01,-0.781831,0.62349,-0.5,0.866025
2,2025-11-09 02:00:00,2025-11-09,2,6,11,2025,9,Dim,0.500000,8.660254e-01,-0.781831,0.62349,-0.5,0.866025
3,2025-11-09 03:00:00,2025-11-09,3,6,11,2025,9,Dim,0.707107,7.071068e-01,-0.781831,0.62349,-0.5,0.866025
4,2025-11-09 04:00:00,2025-11-09,4,6,11,2025,9,Dim,0.866025,5.000000e-01,-0.781831,0.62349,-0.5,0.866025
5,2025-11-09 05:00:00,2025-11-09,5,6,11,2025,9,Dim,0.965926,2.588190e-01,-0.781831,0.62349,-0.5,0.866025
6,2025-11-09 06:00:00,2025-11-09,6,6,11,2025,9,Dim,1.000000,6.123234e-17,-0.781831,0.62349,-0.5,0.866025
7,2025-11-09 07:00:00,2025-11-09,7,6,11,2025,9,Dim,0.965926,-2.588190e-01,-0.781831,0.62349,-0.5,0.866025
8,2025-11-09 08:00:00,2025-11-09,8,6,11,2025,9,Dim,0.866025,-5.000000e-01,-0.781831,0.62349,-0.5,0.866025
9,2025-11-09 09:00:00,2025-11-09,9,6,11,2025,9,Dim,0.707107,-7.071068e-01,-0.781831,0.62349,-0.5,0.866025

In [74]:
prev_meteo = pd.read_csv("previsions_meteo.csv" , sep=";")

prev_meteo['time'] = pd.to_datetime(prev_meteo['time'])

df_merge = pd.merge(df_axe, prev_meteo, left_on='datetime', right_on='time', how='left')

df_merge = df_merge.rename(columns={'temperature_2m (¡C)' : 'Température',
                                    'precipitation (mm)': 'precipitations heure',
                                    'Vent (m/s)' : 'force moyenne vent (m/s)'})
df_merge = df_merge.drop('Unnamed: 0',axis = 1)

df_merge.head()

,datetime,date,heure,dow,mois,annee,jour_mois,jour_semaine,heure_sin,heure_cos,jour_sin,jour_cos,mois_sin,mois_cos,time,Température,precipitations heure,force moyenne vent (m/s)
0,2025-11-09 00:00:00,2025-11-09,0,6,11,2025,9,Dim,0.000000,1.000000,-0.781831,0.62349,-0.5,0.866025,2025-11-09 00:00:00,"9,8",0,"1,305555556"
1,2025-11-09 01:00:00,2025-11-09,1,6,11,2025,9,Dim,0.258819,0.965926,-0.781831,0.62349,-0.5,0.866025,2025-11-09 01:00:00,"9,5",0,"1,361111111"
2,2025-11-09 02:00:00,2025-11-09,2,6,11,2025,9,Dim,0.500000,0.866025,-0.781831,0.62349,-0.5,0.866025,2025-11-09 02:00:00,"9,4",0,"1,333333333"
3,2025-11-09 03:00:00,2025-11-09,3,6,11,2025,9,Dim,0.707107,0.707107,-0.781831,0.62349,-0.5,0.866025,2025-11-09 03:00:00,"9,3",0,"1,027777778"
4,2025-11-09 04:00:00,2025-11-09,4,6,11,2025,9,Dim,0.866025,0.500000,-0.781831,0.62349,-0.5,0.866025,2025-11-09 04:00:00,"8,8",0,1

In [75]:
df = df_merge

def est_weekend(jour):
    if jour == "Dim" or jour == "Sam":
        return 1
    return 0

df['est_weekend'] = df['jour_semaine'].apply(est_weekend)

def est_ferie(num):
    if num == 11:
        return 1
    return 0

df['est_ferie'] = df['jour_mois'].apply(est_ferie)

def est_av_ferie(num):
    if num == 10:
        return 1
    return 0

df['est_avant_ferie'] = df['jour_mois'].apply(est_av_ferie)

df['est_vacances'] = np.nan
df['est_vacances'] = df['est_vacances'].fillna(0)

df['est_avant_vacances'] = np.nan
df['est_avant_vacances'] = df['est_vacances'].fillna(0)

df['est_rentree'] = np.nan
df['est_rentree'] = df['est_rentree'].fillna(0)

def est_pieton(date) :
    date = pd.to_datetime(date)
    inf = pd.to_datetime('2025-11-11 06:00:00')
    sup = pd.to_datetime('2025-11-11 14:00:00')
    if date >= inf and date <= sup :
        return 1
    return 0

df['est_pieton'] = df['datetime'].apply(est_pieton)

def est_hpointe(date):
    heure = date.hour
    if heure == 18 or heure == 19:
        return 1
    return 0

df['est_hpointe'] = df['datetime'].apply(est_hpointe)

df.head(50)

,datetime,date,heure,dow,mois,annee,jour_mois,jour_semaine,heure_sin,heure_cos,...,precipitations heure,force moyenne vent (m/s),est_weekend,est_ferie,est_avant_ferie,est_vacances,est_avant_vacances,est_rentree,est_pieton,est_hpointe
0,2025-11-09 00:00:00,2025-11-09,0,6,11,2025,9,Dim,0.000000e+00,1.000000e+00,...,0,"1,305555556",1,0,0,0.0,0.0,0.0,0,0
1,2025-11-09 01:00:00,2025-11-09,1,6,11,2025,9,Dim,2.588190e-01,9.659258e-01,...,0,"1,361111111",1,0,0,0.0,0.0,0.0,0,0
2,2025-11-09 02:00:00,2025-11-09,2,6,11,2025,9,Dim,5.000000e-01,8.660254e-01,...,0,"1,333333333",1,0,0,0.0,0.0,0.0,0,0
3,2025-11-09 03:00:00,2025-11-09,3,6,11,2025,9,Dim,7.071068e-01,7.071068e-01,...,0,"1,027777778",1,0,0,0.0,0.0,0.0,0,0
4,2025-11-09 04:00:00,2025-11-09,4,6,11,2025,9,Dim,8.660254e-01,5.000000e-01,...,0,1,1,0,0,0.0,0.0,0.0,0,0
5,2025-11-09 05:00:00,2025-11-09,5,6,11,2025,9,Dim,9.659258e-01,2.588190e-01,...,0,1,1,0,0,0.0,0.0,0.0,0,0
6,2025-11-09 06:00:00,2025-11-09,6,6,11,2025,9,Dim,1.000000e+00,6.123234e-17,...,0,"0,805555556",1,0,0,0.0,0.0,0.0,0,0
7,2025-11-09 07:00:00,2025-11-09,7,6,11,2025,9,Dim,9.659258e-01,-2.588190e-01,...,0,"0,583333333",1,0,0,0.0,0.0,0.0,0,0
8,2025-11-09 08:00:00,2025-11-09,8,6,11,2025,9,Dim,8.660254e-01,-5.000000e-01,...,0,"0,444444444",1,0,0,0.0,0.0,0.0,0,0
9,2025-11-09 09:00:00,2025-11-09,9,6,11,2025,9,Dim,7.071068e-01,-7.071068e-01,...,0,"0,444444444",1,0,0,0.0,0.0,0.0,0,0
10,2025-11-09 10:00:00,2025-11-09,10,6,11,2025,9,Dim,5.000000e-01,-8.660254e-01,...,0,"0,638888889",1,0,0,0.0,0.0,0.0,0,0
11,2025-11-09 11:00:00,2025-11-09,11,6,11,2025,9,Dim,2.588190e-01,-9.659258e-01,...,0,"0,722222222",1,0,0,0.0,0.0,0.0,0,0
12,2025-11-09 12:00:00,2025-11-09,12,6,11,2025,9,Dim,1.224647e-16,-1.000000e+00,...,0,"1,166666667",1,0,0,0.0,0.0,0.0,0,0
13,2025-11-09 13:00:00,2025-11-09,13,6,11,2025,9,Dim,-2.588190e-01,-9.659258e-01,...,0,"1,75",1,0,0,0.0,0.0,0.0,0,0
14,2025-11-09 14:00:00,2025-11-09,14,6,11,2025,9,Dim,-5.000000e-01,-8.660254e-01,...,0,"1,888888889",1,0,0,0.0,0.0,0.0,0,0
15,2025-11-09 15:00:00,2025-11-09,15,6,11,2025,9,Dim,-7.071068e-01,-7.071068e-01,...,0,"2,166666667",1,0,0,0.0,0.0,0.0,0,0
16,2025-11-09 16:00:00,2025-11-09,16,6,11,2025,9,Dim,-8.660254e-01,-5.000000e-01,...,0,2,1,0,0,0.0,0.0,0.0,0,0
17,2025-11-09 17:00:00,2025-11-09,17,6,11,2025,9,Dim,-9.659258e-01,-2.588190e-01,...,0,2,1,0,0,0.0,0.0,0.0,0,0
18,2025-11-09 18:00:00,2025-11-09,18,6,11,2025,9,Dim,-1.000000e+00,-1.836970e-16,...,0,"1,833333333",1,0,0,0.0,0.0,0.0,0,1
19,2025-11-09 19:00:00,2025-11-09,19,6,11,2025,9,Dim,-9.659258e-01,2.588190e-01,...,0,"1,861111111",1,0,0,0.0,0.0,0.0,0,1
20,2025-11-09 20:00:00,2025-11-09,20,6,11,2025,9,Dim,-8.660254e-01,5.000000e-01,...,0,"2,166666667",1,0,0,0.0,0.0,0.0,0,0
21,2025-11-09 21:00:00,2025-11-09,21,6,11,2025,9,Dim,-7.071068e-01,7.071068e-01,...,0,"2,166666667",1,0,0,0.0,0.0,0.0,0,0
22,2025-11-09 22:00:00,2025-11-09,22,6,11,2025,9,Dim,-5.000000e-01,8.660254e-01,...,0,"1,666666667",1,0,0,0.0,0.0,0.0,0,0
23,2025-11-09 23:00:00,2025-11-09,23,6,11,2025,9,Dim,-2.588190e-01,9.659258e-01,...,0,"1,305555556",1,0,0,0.0,0.0,0.0,0,0
24,2025-11-10 00:00:00,2025-11-10,0,0,11,2025,10,Lun,0.000000e+00,1.000000e+00,...,0,"1,944444444",0,0,1,0.0,0.0,0.0,0,0
25,2025-11-10 01:00:00,2025-11-10,1,0,11,2025,10,Lun,2.588190e-01,9.659258e-01,...,0,"1,583333333",0,0,1,0.0,0.0,0.0,0,0
26,2025-11-10 02:00:00,2025-11-10,2,0,11,2025,10,Lun,5.000000e-01,8.660254e-01,...,0,"1,722222222",0,0,1,0.0,0.0,0.0,0,0
27,2025-11-10 03:00:00,2025-11-10,3,0,11,2025,10,Lun,7.071068e-01,7.071068e-01,...,0,"1,75",0,0,1,0.0,0.0,0.0,0,0
28,2025-11-10 04:00:00,2025-11-10,4,0,11,2025,10,Lun,8.660254e-01,5.000000e-01,...,0,"1,972222222",0,0,1,0.0,0.0,0.0,0,0
29,2025-11-10 05:00:00,2025-11-10,5,0,11,2025,10,Lun,9.659258e-01,2.588190e-01,...,0,"1,861111111",0,0,1,0.0,0.0,0.0,0,0
30,2025-11-10 06:00:00,2025-11-10,6,0,11,2025,10,Lun,1.000000e+00,6.123234e-17,...,0,"2,25",0,0,1,0.0,0.0,0.0,0,0
31,2025-11-10 07:00:00,2025-11-10,7,0,11,2025,10,Lun,9.659258e-01,-2.588190e-01,...,0,"2,444444444",0,0,1,0.0,0.0,0.0,0,0
32,2025-11-10 08:00:00,2025-11-10,8,0,11,2025,10,Lun,8.660254e-01,-5.000000e-01,...,0,"2,777777778",0,0,1,0.0,0.0,0.0,0,0
33,2025-11-10 09:00:00,2025-11-10,9,0,11,2025,10,Lun,7.071068e-01,-7.071068e-01,...,0,"3,361111111",0,0,1,0.0,0.0,0.0,0,0
34,2025-11-10 10:00:00,2025-11-10,10,0,11,2025,10,Lun,5.000000e-01,-8.660254e-01,...,0,"3,194444444",0,0,1,0.0,0.0,0.0,0,0
35,2025-11-10 11:00:00,2025-11-10,11,0,11,2025,10,Lun,2.588190e-01,-9.659258e-01,...,0,"3,722222222",0,0,1,0.0,0.0,0.0,0,0
36,2025-11-10 12:00:00,2025-11-10,12,0,11,2025,10,Lun,1.224647e-16,-1.000000e+00,...,0,"3,722222222",0,0,1,0.0,0.0,0.0,0,0
37,2025-11-10 13:00:00,2025-11-10,13,0,11,2025,10,Lun,-2.588190e-01,-9.659258e-01,...,"0,1","3,638888889",0,0,1,0.0,0.0,0.0,0,0
38,2025-11-10 14:00:00,2025-11-10,14,0,11,2025,10,Lun,-5.000000e-01,-8.660254e-01,...,0,4,0,0,1,0.0,0.0,0.0,0,0
39,2025-11-10 15:00:00,2025-11-10,15,0,11,2025,10,Lun,-7.071068e-01,-7.071068e-01,...,"0,1","4,027777778",0,0,1,0.0,0.0,0.0,0,0
40,2025-11-10 16:00:00,2025-11-10,16,0,11,2025,10,Lun,-8.660254e-01,-5.000000e-01,...,0,4,0,0,1,0.0,0.0,0.0,0,0
41,2025-11-10 17:00:00,2025-11-10,17,0,11,2025,10,Lun,-9.659258e-01,-2.588190e-01,...,"1,5","4,055555556",0,0,1,0.0,0.0,0.0,0,0
42,2025-11-10 18:00:00,2025-11-10,18,0,11,2025,10,Lun,-1.000000e+00,-1.836970e-16,...,"0,1",4,0,0,1,0.0,0.0,0.0,0,1
43,2025-11-10 19:00:00,2025-11-10,19,0,11,2025,10,Lun,-9.659258e-01,2.588190e-01,...,0,"3,75",0,0,1,0.0,0.0,0.0,0,1
44,2025-11-10 20:00:00,2025-11-10,20,0,11,2025,10,Lun,-8.660254e-01,5.000000e-01,...,0,"3,388888889",0,0,1,0.0,0.0,0.0,0,0
45,2025-11-10 21:00:00,2025-11-10,21,0,11,2025,10,Lun,-7.071068e-01,7.071068e-01,...,0,"3,138888889",0,0,1,0.0,0.0,0.0,0,0
46,2025-11-10 22:00:00,2025-11-10,22,0,11,2025,10,Lun,-5.000000e-01,8.660254e-01,...,0,"2,916666667",0,0,1,0.0,0.0,0.0,0,0
47,2025-11-10 23:00:00,2025-11-10,23,0,11,2025,10,Lun,-2.588190e-01,9.659258e-01,...,0,"2,805555556",0,0,1,0.0,0.0,0.0,0,0
48,2025-11-11 00:00:00,2025-11-11,0,1,11,2025,11,Mar,0.000000e+00,1.000000e+00,...,0,"2,583333333",0,1,0,0.0,0.0,0.0,0,0
49,2025-11-11 01:00:00,2025-11-11,1,1,11,2025,11,Mar,2.588190e-01,9.659258e-01,...,0,"2,388888889",0,1,0,0.0,0.0,0.0,0,0

In [76]:
df.describe()

,datetime,heure,dow,mois,annee,jour_mois,heure_sin,heure_cos,jour_sin,jour_cos,...,mois_cos,time,est_weekend,est_ferie,est_avant_ferie,est_vacances,est_avant_vacances,est_rentree,est_pieton,est_hpointe
count,72,72.000000,72.000000,72.0,72.0,72.000000,7.200000e+01,7.200000e+01,7.200000e+01,72.000000,...,72.000000,72,72.000000,72.000000,72.000000,72.0,72.0,72.0,72.00000,72.000000
mean,2025-11-10 11:30:00,11.500000,2.333333,11.0,2025.0,10.000000,-2.081668e-17,-5.574953e-17,-2.467162e-17,0.748993,...,0.866025,2025-11-10 11:30:00,0.333333,0.333333,0.333333,0.0,0.0,0.0,0.12500,0.083333
min,2025-11-09 00:00:00,0.000000,0.000000,11.0,2025.0,9.000000,-1.000000e+00,-1.000000e+00,-7.818315e-01,0.623490,...,0.866025,2025-11-09 00:00:00,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.00000,0.000000
25%,2025-11-09 17:45:00,5.750000,0.000000,11.0,2025.0,9.000000,-7.071068e-01,-7.071068e-01,-7.818315e-01,0.623490,...,0.866025,2025-11-09 17:45:00,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.00000,0.000000
50%,2025-11-10 11:30:00,11.500000,1.000000,11.0,2025.0,10.000000,6.123234e-17,-6.123234e-17,0.000000e+00,0.623490,...,0.866025,2025-11-10 11:30:00,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.00000,0.000000
75%,2025-11-11 05:15:00,17.250000,6.000000,11.0,2025.0,11.000000,7.071068e-01,7.071068e-01,7.818315e-01,1.000000,...,0.866025,2025-11-11 05:15:00,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.00000,0.000000
max,2025-11-11 23:00:00,23.000000,6.000000,11.0,2025.0,11.000000,1.000000e+00,1.000000e+00,7.818315e-01,1.000000,...,0.866025,2025-11-11 23:00:00,1.000000,1.000000,1.000000,0.0,0.0,0.0,1.00000,1.000000
std,NaN,6.970764,2.643088,0.0,0.0,0.822226,7.120690e-01,7.120690e-01,6.428425e-01,0.178734,...,0.000000,NaN,0.474713,0.474713,0.474713,0.0,0.0,0.0,0.33304,0.278325

In [77]:
df[['est_hpointe', 'datetime']].head(50)

    est_hpointe            datetime
0             0 2025-11-09 00:00:00
1             0 2025-11-09 01:00:00
2             0 2025-11-09 02:00:00
3             0 2025-11-09 03:00:00
4             0 2025-11-09 04:00:00
5             0 2025-11-09 05:00:00
6             0 2025-11-09 06:00:00
7             0 2025-11-09 07:00:00
8             0 2025-11-09 08:00:00
9             0 2025-11-09 09:00:00
10            0 2025-11-09 10:00:00
11            0 2025-11-09 11:00:00
12            0 2025-11-09 12:00:00
13            0 2025-11-09 13:00:00
14            0 2025-11-09 14:00:00
15            0 2025-11-09 15:00:00
16            0 2025-11-09 16:00:00
17            0 2025-11-09 17:00:00
18            1 2025-11-09 18:00:00
19            1 2025-11-09 19:00:00
20            0 2025-11-09 20:00:00
21            0 2025-11-09 21:00:00
22            0 2025-11-09 22:00:00
23            0 2025-11-09 23:00:00
24            0 2025-11-10 00:00:00
25            0 2025-11-10 01:00:00
26            0 2025-11-10 02:00:00
27            0 2025-11-10 03:00:00
28            0 2025-11-10 04:00:00
29            0 2025-11-10 05:00:00
30            0 2025-11-10 06:00:00
31            0 2025-11-10 07:00:00
32            0 2025-11-10 08:00:00
33            0 2025-11-10 09:00:00
34            0 2025-11-10 10:00:00
35            0 2025-11-10 11:00:00
36            0 2025-11-10 12:00:00
37            0 2025-11-10 13:00:00
38            0 2025-11-10 14:00:00
39            0 2025-11-10 15:00:00
40            0 2025-11-10 16:00:00
41            0 2025-11-10 17:00:00
42            1 2025-11-10 18:00:00
43            1 2025-11-10 19:00:00
44            0 2025-11-10 20:00:00
45            0 2025-11-10 21:00:00
46            0 2025-11-10 22:00:00
47            0 2025-11-10 23:00:00
48            0 2025-11-11 00:00:00
49            0 2025-11-11 01:00:00

In [78]:
df['Température'] = df['Température'].str.replace(',','.')
df['precipitations heure'] = df['precipitations heure'].str.replace(',' , '.')
df['force moyenne vent (m/s)'] = df['force moyenne vent (m/s)'].str.replace(',','.')
df['Température'] = pd.to_numeric(df['Température']).astype(float)
df['precipitations heure'] = pd.to_numeric(df['precipitations heure']).astype(float)
df['force moyenne vent (m/s)'] = pd.to_numeric(df['force moyenne vent (m/s)']).astype(float)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   datetime                  72 non-null     datetime64[ns]
 1   date                      72 non-null     object
 2   heure                     72 non-null     int32
 3   dow                       72 non-null     int32
 4   mois                      72 non-null     int32
 5   annee                     72 non-null     int32
 6   jour_mois                 72 non-null     int32
 7   jour_semaine              72 non-null     object
 8   heure_sin                 72 non-null     float64
 9   heure_cos                 72 non-null     float64
 10  jour_sin                  72 non-null     float64
 11  jour_cos                  72 non-null     float64
 12  mois_sin                  72 non-null     float64
 13  mois_cos                  72 non-null     float64
 14  time                      72 non-null     datetime64[ns]
 15  Température               72 non-null     float64
 16  precipitations heure      72 non-null     float64
 17  force moyenne vent (m/s)  72 non-null     float64
 18  est_weekend               72 non-null     int64
 19  est_ferie                 72 non-null     int64
 20  est_avant_ferie           72 non-null     int64
 21  est_vacances              72 non-null     float64
 22  est_avant_vacances        72 non-null     float64
 23  est_rentree               72 non-null     float64
 24  est_pieton                72 non-null     int64
 25  est_hpointe               72 non-null     int64
dtypes: datetime64[ns](2), float64(12), int32(5), int64(5), object(2)
memory usage: 13.3+ KB

In [80]:
df.to_csv("fichier_complet_pour_previsions.csv", sep=";")